import { calculateStats, cancelSession, createInitialState, finishSession, normalizeState, parseImport, serializeExport, startSession, updateSettings } from './domain.mjs';

const KEY='permission-to-smoke:v1', root=document.querySelector('#app');
let state=load(), view=state.activeSession?'pause':'home', tick;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(v||0);
const time=v=>new Date(v).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});
const day=v=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'});

function load(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)))}catch{return createInitialState()}}
function save(next=state){state=next;localStorage.setItem(KEY,JSON.stringify(state));render()}
function button(label,id,cls='primary'){return `<button id="${id}" class="${cls}">${label}</button>`}
function nav(){return `<nav>${['home','history','insights','settings'].map(x=>`<button data-view="${x}" class="${view===x?'active':''}">${x}</button>`).join('')}</nav>`}
function shell(body){return `<header><a data-view="home"><b>⏸ Permission</b><span>to Smoke</span></a><small>Private on this device</small></header><main>${body}</main>${nav()}`}

function home(){const s=calculateStats(state), target=state.settings.dailyTarget, action=state.activeSession?button(`Return to active pause <small>Your ${state.activeSession.delayMinutes}-minute pause is still running</small>`,'resume','urge'):button(`I want to smoke <small>Start a ${state.settings.defaultDelayMinutes}-minute pause</small>`,'start','urge');return `
<section class="hero"><p>${new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'})}</p><h1>An urge is a signal.<br><em>Not an instruction.</em></h1><p>Take one honest pause before deciding. No guilt, no account, no streak pressure.</p>${action}</section>
<section class="stats"><article><span>Smoked today</span><strong>${s.smokedToday}</strong><small>Target ${target}</small></article><article><span>Urges skipped</span><strong>${s.skippedToday}</strong><small>${s.targetRemaining} target remaining</small></article><article><span>Potential spend protected</span><strong>${esc(state.settings.currency)}${money(s.moneyProtected)}</strong><small>Self-reported estimate</small></article></section>
<section><div class="title"><h2>Recent decisions</h2><button data-view="history">View all</button></div>${recent(3)}</section>
<aside>This is a reflection and tracking tool, not medical advice or smoking-cessation treatment.</aside>`}

function checkin(){return `<section class="card"><button id="close" class="x">×</button><p class="eyebrow">Step 1 of 2</p><h1>Notice what is happening.</h1><p>Name the urge before it runs the next minute.</p><form id="checkin"><fieldset><legend>Urge strength</legend><div class="choices">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="intensity" value="${n}" ${n===3?'checked':''}><span>${n}</span></label>`).join('')}</div></fieldset><fieldset><legend>Trigger</legend><div class="triggers">${['Stress','After food','Social','Boredom','Habit','Other'].map((x,i)=>`<label><input type="radio" name="trigger" value="${x}" ${i===0?'checked':''}><span>${x}</span></label>`).join('')}</div></fieldset><label>Optional note<textarea name="note" maxlength="240" placeholder="What do you need right now?"></textarea></label>${button('Begin the pause','begin')}</form></section>`}

function pause(){const a=state.activeSession;return `<section class="pause"><button id="cancel" class="x">×</button><div class="timer"><strong id="clock">${a.delayMinutes}:00</strong><small>remaining</small></div><h1>Let the wave pass.</h1><p>Slow inhale for 4. Hold for 2. Exhale for 6.</p><div class="pills"><span>Urge ${a.intensity}/5</span><span>${esc(a.trigger||'Unspecified')}</span></div>${button("I'm ready to decide",'decide','secondary')}</section>`}
function decision(){const a=state.activeSession;return `<section class="card centered"><p class="eyebrow">The pause is complete</p><h1>What did you choose?</h1><p>Both answers are useful data. Honest logging matters more than a perfect day.</p><div class="outcomes">${button('✓ I skipped it','skipped','positive')}${button('I smoked','smoked','neutral')}</div><small>Started ${time(a.startedAt)} · ${a.delayMinutes}-minute pause</small></section>`}

function recent(limit=999){const xs=state.sessions.slice(0,limit);if(!xs.length)return `<div class="empty">Your decisions will appear here after the first pause.</div>`;return `<div class="list">${xs.map(x=>`<article><i class="${x.outcome}">${x.outcome==='skipped'?'✓':'•'}</i><div><b>${x.outcome==='skipped'?'Skipped the cigarette':'Logged a cigarette'}</b><small>${esc(x.trigger||'No trigger')} · urge ${x.intensity}/5</small></div><time>${day(x.completedAt)} ${time(x.completedAt)}</time></article>`).join('')}</div>`}
function history(){return `<section class="pagehead"><p>Your record</p><h1>History</h1><span>Honest data, no judgement.</span></section>${recent()}`}
function insights(){const s=calculateStats(state),max=Math.max(1,...s.last7.flatMap(d=>[d.smoked,d.skipped]));return `<section class="pagehead"><p>Patterns, not grades</p><h1>Insights</h1><span>Last seven days and all-time totals.</span></section><section class="stats"><article><span>Skipped</span><strong>${s.allSkipped}</strong></article><article><span>Smoked</span><strong>${s.allSmoked}</strong></article><article><span>Skip rate</span><strong>${s.successRate}%</strong></article></section><section class="chart">${s.last7.map(d=>`<div><div class="bars"><i class="smoked" style="height:${d.smoked/max*100}%"></i><i class="skipped" style="height:${d.skipped/max*100}%"></i></div><small>${d.label}</small></div>`).join('')}</section><aside>${s.allSkipped+s.allSmoked?'Look for repeated situations. The goal is a clearer choice, not a perfect score.':'Log a few urges first; patterns will appear here.'}</aside>`}
function settings(){const s=state.settings;return `<section class="pagehead"><p>Make the pause yours</p><h1>Settings</h1><span>Changes stay on this device.</span></section><form id="settings" class="card formgrid"><label>Daily smoking target<input name="dailyTarget" type="number" min="0" max="50" value="${s.dailyTarget}"></label><label>Default pause (minutes)<input name="defaultDelayMinutes" type="number" min="1" max="60" value="${s.defaultDelayMinutes}"></label><label>Usual cigarettes/day<input name="baselinePerDay" type="number" min="0" max="100" value="${s.baselinePerDay}"></label><label>Cost per cigarette<input name="cigaretteCost" type="number" min="0" max="10000" step="0.01" value="${s.cigaretteCost}"></label><label class="check"><input name="reducedMotion" type="checkbox" ${s.reducedMotion?'checked':''}> Reduce motion</label>${button('Save settings','save')}</form><section class="card data"><div><h2>Your data</h2><p>Export a JSON backup, import one, or permanently clear this browser.</p></div><div>${button('Export','export','secondary')}<label class="secondary file">Import<input id="import" type="file" accept="application/json,.json"></label>${button('Reset','reset','danger')}</div></section>`}

function render(){clearInterval(tick);document.documentElement.classList.toggle('reduce-motion',state.settings.reducedMotion);const screens={home,checkin,pause,decision,history,insights,settings};root.innerHTML=shell((screens[view]||home)());wire();if(view==='pause')clock()}
function wire(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});
 document.querySelector('#start')?.addEventListener('click',()=>{view=state.activeSession?'pause':'checkin';render()});document.querySelector('#resume')?.addEventListener('click',()=>{view='pause';render()});document.querySelector('#close')?.addEventListener('click',()=>{view='home';render()});
 document.querySelector('#checkin')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state=startSession(state,{intensity:f.get('intensity'),trigger:f.get('trigger'),note:f.get('note'),delayMinutes:state.settings.defaultDelayMinutes});view='pause';save()});
 document.querySelector('#cancel')?.addEventListener('click',()=>{if(confirm('Cancel this pause without saving it?')){state=cancelSession(state);view='home';save()}});document.querySelector('#decide')?.addEventListener('click',()=>{view='decision';render()});
 document.querySelector('#skipped')?.addEventListener('click',()=>finish('skipped'));document.querySelector('#smoked')?.addEventListener('click',()=>finish('smoked'));
 document.querySelector('#settings')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state=updateSettings(state,{dailyTarget:f.get('dailyTarget'),defaultDelayMinutes:f.get('defaultDelayMinutes'),baselinePerDay:f.get('baselinePerDay'),cigaretteCost:f.get('cigaretteCost'),reducedMotion:f.get('reducedMotion')==='on'});save();alert('Settings saved')});
 document.querySelector('#export')?.addEventListener('click',exportData);document.querySelector('#import')?.addEventListener('change',importData);document.querySelector('#reset')?.addEventListener('click',reset)}
function finish(outcome){state=finishSession(state,outcome);view='home';save()}
function clock(){const update=()=>{const ms=Math.max(0,new Date(state.activeSession.endsAt)-Date.now()),sec=Math.ceil(ms/1000),el=document.querySelector('#clock');if(el)el.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;if(ms<=0){clearInterval(tick);view='decision';render()}};update();tick=setInterval(update,1000)}
function exportData(){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([serializeExport(state)],{type:'application/json'}));a.href=u;a.download=`permission-to-smoke-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)}
async function importData(e){const f=e.target.files?.[0];if(!f)return;try{const next=parseImport(await f.text());if(confirm(`Import ${next.sessions.length} decisions and replace current data?`))save(next)}catch{alert('Invalid backup file')}e.target.value=''}
function reset(){if(confirm('Permanently delete all saved data from this browser?')){localStorage.removeItem(KEY);state=createInitialState();view='home';render()}}
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}));
render();
